Update rtsetup

diff --git a/rtsetup b/rtsetup
--- a/rtsetup
+++ b/rtsetup
@@ -67,12 +67,6 @@ if hash rtorrent >> /dev/null 2>&1; then
 else
   echo "rtorrent was not installed"
 fi
-echo
-echo "FTP Port set to $ftpport"
-echo
-echo "IMPORTANT - SSH Port has been set to: $sshport"
-echo "IMPORTANT - SSH Port has been set to: $sshport"
-echo "IMPORTANT - SSH Port has been set to: $sshport"
 exit 1
 }
 
@@ -201,7 +195,8 @@ if [ "$relno" = "10" ] || [ "$(lsb_release -sr)" = "19.10" ]; then phpver=php7.3
 if [ "$relno" = "20" ] || [ "$(lsb_release -sr)" = "20.04" ] || [ "$relno" = "11" ]; then phpver=php7.4; phploc=/etc/php/7.4; libcver=libcurl4; fi
 if [ "$relno" = "21" ] || [ "$(lsb_release -sr)" = "21.04" ]; then phpver=php7.4; phploc=/etc/php/7.4; libcver=libcurl4; fi
 if [ "$relno" = "22" ] || [ "$(lsb_release -sr)" = "22.04" ]; then phpver=php7.4; phploc=/etc/php/7.4; libcver=libcurl4; fi
-if [ "$relno" = "23" ] || [ "$(lsb_release -sr)" = "22.04" ]; then phpver=php8.2; phploc=/etc/php/8.2; libcver=libcurl4; if ! installed unrar; then sudo apt install php8.2-cli -y; fi; fi
+if [ "$relno" = "23" ] || [ "$relno" = "24" ]; then phpver=php8.2; phploc=/etc/php/8.2; libcver=libcurl4;
+if ! installed php8.2-cli; then sudo apt install php8.2-cli -y; fi; if ! installed php8.2-mysql; then sudo apt install php8.2-mysql -y; fi; if ! installed php8.2-mbstring; then sudo apt install php8.2-mbstring && sudo service nginx reload; fi; if ! installed php-gd; then sudo apt install php-gd -y; fi; if ! installed geoip-bin; then sudo apt install geoip-bin -y; fi; if ! installed php8.2-cgi; then sudo apt-get install php8.2-cgi; fi; fi
 
 #get server ip(s)
 serveripa=$(ip route get 8.8.8.8 | awk 'NR==1 {print $7}'); serveripb=$(wget -qO- --timeout=3 ipecho.net/plain); serveripc=$(wget -qO- --timeout=3 ipinfo.io/ip)
@@ -226,7 +221,7 @@ cronline1="@reboot sleep 10; /usr/local/bin/rtcheck irssi rtorrent"
 cronline2="*/10 * * * * /usr/local/bin/rtcheck irssi rtorrent"
 dlflag=1; portdefault=0; skip_rt=1; sshport=''; rudevflag=0; rurelease=master
 passfile='/etc/nginx/.htpasswd'
-package_list="sudo nano autoconf automake build-essential ca-certificates comerr-dev curl dtach htop irssi bmon libcppunit-dev $libcver libncurses5-dev libterm-readline-gnu-perl libsigc++-2.0-dev libperl-dev libtool libxml2-dev ncurses-base ncurses-term ntp patch pkg-config $phpver-fpm $phpver $phpver-cli $phpver-dev $phpver-curl php-geoip $phpver-xmlrpc $phpver-xml $phpver-zip screen subversion texinfo unzip zlib1g-dev libcurl4-openssl-dev mediainfo software-properties-common $phpver-json nginx-full apache2-utils git libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl libjson-rpc-perl libarchive-zip-perl iotop varnish"
+package_list="sudo nano autoconf automake build-essential ca-certificates comerr-dev curl dtach htop irssi bmon libcppunit-dev $libcver libncurses5-dev libterm-readline-gnu-perl libsigc++-2.0-dev libperl-dev libtool libxml2-dev ncurses-base ncurses-term ntp patch pkg-config $phpver-fpm $phpver $phpver-cli $phpver-dev $phpver-curl $phpver-xmlrpc $phpver-xml $phpver-zip screen subversion texinfo unzip zlib1g-dev libcurl4-openssl-dev mediainfo software-properties-common $phpver-json nginx-full apache2-utils git libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl libjson-rpc-perl libarchive-zip-perl iotop varnish"
 Install_list=""; unixpass=""; passflag=0; forceyes=1; selfsign=1; rut_add_users=1;
 
 ###############################
@@ -448,9 +443,7 @@ for package_name in $package_list
   done
 
 # Installs a package needed to prevent arm64 architectures from "WARNING: Unable to start rtorrent"
-if [ "$(uname --m)" == "aarch64" ] || [ "$(dpkg --print-architecture)" == "arm64" ] ; then
-    aptitude -q=5 -y install libxmlrpc-core-c3-dev >> $logfile 2>&1
-fi
+if [ "$(uname --m)" == "aarch64" ] || [ "$(dpkg --print-architecture)" == "arm64" ] ; then aptitude -q=5 -y install libxmlrpc-core-c3-dev >> $logfile 2>&1; fi
 
 # Pass 1: Attempt to install the required packages on the install list
 test -z "$install_list" || aptitude -q=5 -y install $install_list >> $logfile 2>&1
@@ -470,7 +463,6 @@ test -z "$install_list" || aptitude -q=5 -y install $install_list >> $logfile 2>
 if ! [ $? = 0 ]; then
   # Attempt to restart nginx before we exit the script for failure
   service nginx restart >> $logfile 2>&1
-  
   echo "Problem installing packages. Check log and rerun once it is resolved" && exit
 fi
 
@@ -494,77 +486,10 @@ if [ "$(lsb_release -sr)" = "20.04" ]; then
 fi
 
 #install unrar package
-if [ $osname = "Debian" ] && ! installed unrar; then
-  echo "Installing rar/unrar"
-  cd $home
-  attempts=0
-  until [ -d rar ] || [ $attempts -gt 5 ]
-  do
-    attempts=$(( $attempts + 1 ))
-    if [ "$(uname -m)" = "x86_64" ]; then
-      wget http://www.rarlab.com/rar/rarlinux-x64-5.7.1.tar.gz >> $logfile 2>&1
-      tar xvzf rarlinux-x64-5.7.1.tar.gz >> $logfile 2>&1
-      rm rarlinux-x64-5.7.1.tar.gz
-    elif [ "$(uname -m)" = "x86_32" ]; then
-      wget http://www.rarlab.com/rar/rarlinux-5.7.1.tar.gz >> $logfile 2>&1
-      tar xvzf rarlinux-5.7.1.tar.gz >> $logfile 2>&1
-      rm rarlinux-5.7.1.tar.gz
-    fi
-  done
-  if [ -d rar ]; then
-    cp $home/rar/rar /bin/rar
-    cp $home/rar/unrar /bin/unrar
-    rm -r $home/rar
-  fi
-elif [ $osname = "Ubuntu" ] && ! installed unrar; then echo "Installing rar/unrar"; aptitude -q=5 -y install unrar >> $logfile 2>&1
-fi
-if installed unrar; then echo "App: rar/unrar is installed"; else echo "rar/unrar install failed"; fi
-
-setup_resolvconf_file() {
-  # Remove the symlinked resolv.conf file
-  rm /etc/resolv.conf >> $logfile 2>&1
-
-  # Create new resolv.conf file. Add dnsmasq and cloudflare dns server
-  bash -c 'echo nameserver 127.0.0.1 >> /etc/resolv.conf'
-  bash -c 'echo nameserver 1.1.1.1 >> /etc/resolv.conf'
-
-  # Make resolv.conf file immutable to prevent DNS issues
-  chattr +i /etc/resolv.conf >> $logfile 2>&1
-}
-
-### INSTALL DNSMASQ ###
-echo "Installing Dnsmasq"
-
-# Disable the resolved service
-systemctl disable systemd-resolved >> $logfile 2>&1
-systemctl stop systemd-resolved >> $logfile 2>&1
-
-# Remove immutablity on resolv.conf file (if present)
-chattr -i /etc/resolv.conf >> $logfile 2>&1
-
-# Run procress to setup resolvconf file
-setup_resolvconf_file;
-
-# Install dnsmasq from repository
-aptitude -q=5 -y install dnsmasq >> $logfile 2>&1
-
-### INSTALL resolvconf ###
-echo "Installing resolvconf"
-
-# Remove immutablity on resolv.conf file
-chattr -i /etc/resolv.conf >> $logfile 2>&1
-
-# Install resolvconf
-aptitude -q=5 -y install resolvconf >> $logfile 2>&1
-
-# Run procress to setup resolvconf file
-setup_resolvconf_file;
+if ! installed unrar; then echo "Installing rar/unrar"; sudo apt install unrar; fi; if installed unrar; then echo "App: rar/unrar is installed"; else echo "rar/unrar install failed"; fi
 
 #install ffmpeg
-if ! [ $osname = "Raspbian" ] ! installed ffmpeg; then
-  echo "Installing ffmpeg"
-  sudo apt install ffmpeg -y >> $logfile 2>&1
-fi
+if ! installed ffmpeg; then echo "Installing ffmpeg"; sudo apt install ffmpeg -y >> $logfile 2>&1; else echo "FFmpeg already installed"; fi
 
 echo "Completed installation of required packages"
 
@@ -577,65 +502,6 @@ cd $home
 sed -i '/hard nofile/ d' /etc/security/limits.conf
 sed -i '/soft nofile/ d' /etc/security/limits.conf
 sed -i '$ i\* hard nofile 65535\n* soft nofile 65535' /etc/security/limits.conf
-
-
-###############################
-### CONFIGURE SSH ###
-###############################
-
-#echo "Configuring SSH" | tee -a $logfile
-
-#oldsshport=$(grep -P '^[#\s]*Port ' /etc/ssh/sshd_config | sed 's/[^0-9]*//g')
-
-#if [ "$portdefault" = "0" ] && [ "$oldsshport" = "22" ]; then
- # sshport=22
-#elif [ "$oldsshport" = "22" ] && [ "$portdefault" = "1" ]; then
- # sshport=$(random 21000 29000)
-#else
- # sshport=$oldsshport
-#fi
-
-#sed -i "/^\(\s\|#\)*Port / c\Port $sshport" /etc/ssh/sshd_config
-#sed -i "/^\(\s\|#\)*X11Forwarding /c\X11Forwarding no" /etc/ssh/sshd_config
-#sed -i '/^\s*PasswordAuthentication no/ c\#PasswordAuthentication no' /etc/ssh/sshd_config
-
-#echo >> /etc/ssh/sshd_config
-#grep -Pq "^[#\s]*UsePAM" /etc/ssh/sshd_config && sed -i '/^\(\s\|#\)*UsePAM/ c\UsePAM yes' /etc/ssh/sshd_config || echo "UsePAM yes" >> /etc/ssh/sshd_config
-#grep -Pq "^[#\s]*UseDNS" /etc/ssh/sshd_config && sed -i '/^\(\s\|#\)*UseDNS/ c\UseDNS no' /etc/ssh/sshd_config || echo "UseDNS no" >> /etc/ssh/sshd_config
-
-#if [ -z "$(grep sshuser /etc/group)" ]; then
-#groupadd sshuser
-#fi
-
-#allowlist=$(grep ^AllowUsers /etc/ssh/sshd_config)
-#if ! [ -z "$allowlist" ]; then
- # for ssh_user in $allowlist
- #   do
- #     if   [ ! "$ssh_user" = "AllowUsers" ] && [ "$(groups $ssh_user 2> /dev/null | grep -E ' sudo(\s|$)')" = "" ]; then
-  #      adduser $ssh_user sshuser
-  #    fi
- #   done
-#  sed -i "/$allowlist/ d" /etc/ssh/sshd_config
-#fi
-#grep "AllowGroups sudo sshuser" /etc/ssh/sshd_config > /dev/null || echo "AllowGroups sudo sshuser" >> /etc/ssh/sshd_config
-
-#service ssh restart 1>> $logfile
-#sshport=$(grep 'Port ' /etc/ssh/sshd_config | sed 's/[^0-9]*//g')
-#echo "SSH port set to $sshport"
-
-###############################
-### CONFIGURE DNSMASQ ###
-###############################
-
-# Update configuration varriables in /etc/dnsmasq.conf
-sed -i "s/#port=5353/port=53/g" /etc/dnsmasq.conf
-sed -i "s/#domain-needed/domain-needed/g" /etc/dnsmasq.conf
-sed -i "s/#bogus-priv/bogus-priv/g" /etc/dnsmasq.conf
-sed -i "s/#strict-order/strict-order/g" /etc/dnsmasq.conf
-sed -i "s/#listen-address=/listen-address=127.0.0.1/g" /etc/dnsmasq.conf
-
-# Restart dnsmasq service when completed
-service dnsmasq restart >> $logfile 2>&1
 
 ###############################
 ### INSTALL NGINX ###
@@ -662,6 +528,7 @@ fi
 chown www-data:www-data $passfile
 chmod 640 $passfile
 
+echo "Using PHP Location: $phploc" | tee -a $logfile
 sed -i "s/user www-data;/user www-data www-data;/g" /etc/nginx/nginx.conf
 sed -i "s/worker_processes 4;/worker_processes 1;/g" /etc/nginx/nginx.conf
 sed -i "s/pid \/run\/nginx\.pid;/pid \/var\/run\/nginx\.pid;/g" /etc/nginx/nginx.conf
@@ -702,7 +569,7 @@ echo "        expires 30d;" >> /etc/nginx/conf.d/cache
 echo "}" >> /etc/nginx/conf.d/cache
 
 # We only need to update the server name & proxy_redirect here. The certificate and key is added by the configuration file.
-sed -i "/^\(\s\|#\)*server_name/ c\        server_name $serverip;" /etc/nginx/sites-available/default
+sed -i "/^\(\s\|#\)*server_name/ c\        #server_name $serverip;" /etc/nginx/sites-available/default
 sed -i "/^\(\s\|#\)*proxy_redirect/ c\        proxy_redirect http://localhost:6081 https://$serverip;" /etc/nginx/sites-available/default
 
 service nginx restart && service $phpver-fpm restart
@@ -712,27 +579,14 @@ if [ $dlflag = 0 ]; then
 fi
 
 ###############################
-### Configure Varnish Cache ###
-###############################
-if [ ! -f "/etc/varnish/default.vcl" ]; then
-  echo "Configuring Varnish Cache" | tee -a $logfile
-  cp -f /etc/rtinst/conf/varnish.service /usr/lib/systemd/system/varnish.service >> $logfile 2>&1
-  cp -f /etc/rtinst/conf/varnish.vcl /etc/varnish/default.vcl >> $logfile 2>&1
-  systemctl daemon-reload >> $logfile 2>&1
-  service varnish restart >> $logfile 2>&1
-fi
-
-###############################
 ### INSTALL RTORRENT ###
 ###############################
 
 if [ $skip_rt = 1 ]; then
-  if [ -z $rtorrentrel ]; then
-    rtorrentrel='latest'
-  fi
+  if [ -z $rtorrentrel ]; then rtorrentrel='latest'; fi
   export home
   # call the script rtupdate to install lib/rtorrent
-  rtupdate $rtorrentrel || early_exit
+  rtupdate $rtorrentrel || sudo apt -y install rtorrent; #  early_exit;
   export -n home
   echo "Configuring rtorrent" | tee -a $logfile
   cd $home
@@ -844,7 +698,7 @@ fi
 
 
 # Copy GeoIP database for ruTorrent geoip plugin
-cp -r /etc/rtinst/GeoIP /usr/share
+if [ -d "/etc/rtinst/GeoIP" ]; then cp -r /etc/rtinst/GeoIP /usr/share; fi
 
 ###############################
 ### SSL CERTIFICATES ###
